# Generated by Django 3.2 on 2023-05-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answerstate',
            fields=[
                ('anid', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('qid', models.IntegerField(max_length=5, null=True)),
                ('state', models.IntegerField(max_length=5, null=True)),
                ('tnid', models.IntegerField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bj',
            fields=[
                ('bjid', models.IntegerField(max_length=1, primary_key=True, serialize=False)),
                ('bjname', models.CharField(max_length=10, null=True)),
                ('tid', models.IntegerField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='questiontype',
            fields=[
                ('qtid', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('qtname', models.CharField(max_length=10, null=True)),
                ('score', models.IntegerField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_admin',
            fields=[
                ('uid', models.IntegerField(max_length=1, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_qprelationq',
            fields=[
                ('rid', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('num', models.IntegerField(max_length=3, null=True)),
                ('qpid', models.IntegerField(max_length=3)),
                ('qid', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='tb_question',
            fields=[
                ('qid', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('qcontent', models.CharField(max_length=100)),
                ('aoption', models.CharField(max_length=100, null=True)),
                ('boption', models.CharField(max_length=100, null=True)),
                ('coption', models.CharField(max_length=100, null=True)),
                ('doption', models.CharField(max_length=100, null=True)),
                ('ganswer', models.CharField(max_length=1, null=True)),
                ('ganalysis', models.CharField(max_length=200, null=True)),
                ('oword', models.CharField(max_length=100, null=True)),
                ('gscope', models.CharField(max_length=100, null=True)),
                ('gdifficulty', models.CharField(max_length=5, null=True)),
                ('gdate', models.DateField(null=True)),
                ('gtid', models.IntegerField(max_length=3, null=True)),
                ('tid', models.IntegerField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_questionpaper',
            fields=[
                ('qpid', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('qpdate', models.DateField()),
                ('time', models.IntegerField()),
                ('tid', models.IntegerField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_testcontrol',
            fields=[
                ('tcid', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('state', models.IntegerField(max_length=3, null=True)),
                ('mode', models.IntegerField(max_length=3)),
                ('qpid', models.IntegerField(max_length=3, null=True)),
                ('tname', models.CharField(max_length=20, null=True)),
                ('tdate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_testnote',
            fields=[
                ('tnid', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('sid', models.IntegerField(max_length=10, null=True)),
                ('qpid', models.IntegerField(max_length=3, null=True)),
                ('tname', models.CharField(max_length=20, null=True)),
                ('stime', models.DateField(null=True)),
                ('etime', models.DateField(null=True)),
                ('score', models.IntegerField(max_length=3, null=True)),
            ],
        ),
    ]
